version: '2'
services:
  nginx:
    image: nginx:1.13.9-alpine
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ./typecho:/app
      - ./typecho.conf:/etc/nginx/conf.d/default.conf
      - logs:/var/log/nginx
    links:
      - php-fpm
    depends_on:
      - php-fpm
  php-fpm:
    image: typecho-php-fpm:latest
    restart: always
    volumes:
      - ./typecho:/app
      - ./php.ini:/usr/local/etc/php/php.ini
volumes:
  logs:
